import { NextRequest, NextResponse } from "next/server"
import { AuditAction } from "@prisma/client"

import { prisma } from "@/lib/db"
import { withBotAuth, type BotAuthenticatedRequest, logBotAuditEvent } from "@/lib/bot-auth"

export const runtime = "nodejs"
export const dynamic = "force-dynamic"

type DraftTicketBody = {
  title?: string
  summary?: string
  issue?: string
  recommendation?: string
  priority?: string
  depositId?: string
  lineId?: string
  revenueScheduleId?: string
}

const DRAFT_PERMISSIONS = ["reconciliation.view", "tickets.manage", "tickets.read"]

function stringValue(value: unknown) {
  return typeof value === "string" ? value.trim() : ""
}

function priorityValue(value: string) {
  const normalized = value.trim().toLowerCase()
  if (normalized === "critical") return "Critical"
  if (normalized === "high") return "High"
  if (normalized === "low") return "Low"
  return "Medium"
}

async function buildContext(request: BotAuthenticatedRequest, body: DraftTicketBody) {
  const depositId = stringValue(body.depositId)
  const lineId = stringValue(body.lineId)
  const revenueScheduleId = stringValue(body.revenueScheduleId)

  const [deposit, line, schedule] = await Promise.all([
    depositId
      ? prisma.deposit.findFirst({
          where: { id: depositId, tenantId: request.user.tenantId },
          select: { id: true, depositName: true, status: true, paymentDate: true },
        })
      : null,
    lineId
      ? prisma.depositLineItem.findFirst({
          where: { id: lineId, tenantId: request.user.tenantId },
          select: {
            id: true,
            lineNumber: true,
            accountNameRaw: true,
            vendorNameRaw: true,
            productNameRaw: true,
            usage: true,
            commission: true,
            status: true,
          },
        })
      : null,
    revenueScheduleId
      ? prisma.revenueSchedule.findFirst({
          where: { id: revenueScheduleId, tenantId: request.user.tenantId, deletedAt: null },
          select: {
            id: true,
            scheduleNumber: true,
            status: true,
            account: { select: { accountName: true } },
            product: { select: { productNameHouse: true, productNameVendor: true } },
          },
        })
      : null,
  ])

  return { deposit, line, schedule }
}

export async function POST(request: NextRequest) {
  return withBotAuth(request, DRAFT_PERMISSIONS, async (req) => {
    const body = (await request.json().catch(() => null)) as DraftTicketBody | null
    const issue = stringValue(body?.issue || body?.summary)
    const recommendation = stringValue(body?.recommendation)
    const title = stringValue(body?.title) || (issue ? `Review: ${issue.slice(0, 80)}` : "Review reconciliation exception")
    const context = await buildContext(req, body ?? {})

    const descriptionLines = [
      issue ? `Issue: ${issue}` : null,
      recommendation ? `Recommendation: ${recommendation}` : null,
      context.deposit
        ? `Deposit: ${context.deposit.depositName ?? context.deposit.id} (${context.deposit.status})`
        : null,
      context.line
        ? `Line: ${context.line.lineNumber ?? context.line.id} | ${context.line.accountNameRaw ?? "Unknown account"} | ${context.line.productNameRaw ?? "Unknown product"} | ${context.line.status}`
        : null,
      context.schedule
        ? `Revenue Schedule: ${context.schedule.scheduleNumber ?? context.schedule.id} | ${context.schedule.account?.accountName ?? "Unknown account"} | ${context.schedule.product?.productNameHouse ?? context.schedule.product?.productNameVendor ?? "Unknown product"} | ${context.schedule.status}`
        : null,
      "Draft generated by Commissable Bot. No ticket was created.",
    ].filter(Boolean)

    await logBotAuditEvent({
      request: req,
      action: AuditAction.Export,
      entityName: "Ticket",
      entityId: "draft",
      metadata: {
        botRoute: "tickets.draft",
        hasDeposit: Boolean(context.deposit),
        hasLine: Boolean(context.line),
        hasSchedule: Boolean(context.schedule),
      },
    })

    return NextResponse.json({
      status: "success",
      data: {
        draft: {
          title,
          description: descriptionLines.join("\n"),
          priority: priorityValue(stringValue(body?.priority)),
          related: {
            depositId: context.deposit?.id ?? null,
            lineId: context.line?.id ?? null,
            revenueScheduleId: context.schedule?.id ?? null,
          },
          persisted: false,
        },
      },
      context: {
        tenant_id: req.user.tenantId,
      },
    })
  })
}
